config/routes.rb
Gradesys::Application.routes.draw do
  get "grade/index"
  post "grade/enter"
  get "grade/feng_guan_zhuan_yuan"
  get "grade/zhuan_ke_feng_hui"
  get "grade/error_state"
  get "grade/add_options"
  get "grade/fgzy_update_attr"
  get "grade/leave_message"
  get "grade/change_right_bar"
  post "grade/submit_fgzy"
  get "grade/change_header"

   root 'grade#index'

  

end

app/models/feng_score.rb
class FengScore < ActiveRecord::Base
	belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
end

app/models/party.rb
class Party < ActiveRecord::Base
	has_many :user_binding
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :feng_score
	has_one :message
	has_many :user_binding
end

app/models/user_binding.rb
class UserBinding < ActiveRecord::Base
	belongs_to :party
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grade_controller.rb
class GradeController < ApplicationController

  layout 'login', :only=>[:index]

  def index
  	@user= User.new
  end

  def enter
	  	username=params[:user][:username]
	  	user=User.find_by_username(username)
	  	if user
	  		if user.password== params[:user][:password]
	  			cookies[:id]= user.id
	  			case user.state
	  			when 0
	  				redirect_to :action=>'feng_guan_zhuan_yuan'
	  			when 1
	  				render :action=>'zhuan_ke_feng_hui'
	  			else
	  				render :action=>' error_state'
	  		    end
	  		else
		  		redirect_to root_path
	  		end
	  	else
	  		redirect_to root_path
	  	end
  end

  def feng_guan_zhuan_yuan
  	@user= User.find(cookies[:id])
    @feng_score= FengScore.new
  end

  def submit_fgzy
    @score= FengScore.new(feng_score_params)
    @score.save
    redirect_to :action=>'feng_guan_zhuan_yuan'
  end

  def zhuan_ke_feng_hui
  	@user= User.find( cookies[:id])
  end

  def error_state

  end

  def add_options
    bindings= UserBinding.where("user_id= #{cookies[:id]}" )
    parties=[]
    bindings.each do |b|
      parties<< Party.find( b.party_id)
    end
  	render :json=> parties
  end


  def leave_message
    message= params[:message]
    id= cookies[:id]

    new_msg= Message.new( content: message, user: id)
    new_msg.save
    render :json=>1

  end

  def change_right_bar
    data=[]
    done=[]
    done_count=0
    undone=[]
    undone_count=0
    party= Party.find( params[:id]).name
    data[0]= party

    done_temp= UserBinding.where(" party_id=#{ params[:id]}")
    done_temp.each do |d|
      if ( d.user.state==1 && d.user.rule== 0)
        done<< d.user.username
        done_count= done_count+1
      elsif ( d.user.state==1 && d.user.rule ==1)
        undone<< d.user.username
        undone_count =undone_count+1
      end
    end

    data[1]= done_count
    data[2]= done
    data[3]= undone_count
    data[4]= undone
    if ( done_count==0 && undone_count==0)
      data[5]=0
    else
      data[5]= 100*( done_count.to_f/( done_count+ undone_count))
    end

    render :json=> data
  end

  def change_header
    id= cookies[:id]
    user= User.find( id).username
    party= Party.find( params[:id]).name
    data=[]
    data[0]=user
    data[1]=party
    render :json=> data
  end

  private

  def feng_score_params
    params.require(:feng_score).permit(:user_id, :party_id,
                                       :xshy, :xshy_detail,
                                       :jxyx, :jxyx_detail,
                                       :astj, :astj_detail,
                                       :wchy, :wchy_detail,
                                       :zxhy, :zxhy_detail,
                                       :zjsf, :zjsf_detail,
                                       :dzyl, :dzyl_detail,
                                       :rxxh, :rxxh_detail,
                                       :zsxg, :zsxg_detail,
                                       :zsgz, :zsgz_detail,
                                       :rzzx, :rzzx_detail,
                                       :xshd, :xshd_detail)
  end
=begin
  def fgzy_update_attr
    flag  = params[:flag]
    value = params[:value]
    detail= params[:detail]
    party = params[:party]
    id= cookies[:id]

    score= FengScore.find(:first, :conditions=>[" user_id= ? and party_id=?", id, party])
    if !score
      score=FengScore.new( user_id: id, party_id: party)
      score.save
      score= FengScore.find(:first, :conditions=>[" user_id= ? and party_id=?", id, party])
    end

    case flag
    when "1"
      score.update_attributes( :xshy=> value, :xshy_detail=> detail)
    when "2"
      score.update_attributes( :jxyx=> value, :jxyx_detail=> detail)
    when "3"
      score.update_attributes( :astj=> value, :astj_detail=> detail)
    when "4"
      score.update_attributes( :wchy=> value, :wchy_detail=> detail)
    when "5"
      score.update_attributes( :zxhy=> value, :zxhy_detail=> detail)
    when "6"
      score.update_attributes( :zjsf=> value, :zjsf_detail=> detail)
    when "7"
      score.update_attributes( :dzyl=> value, :dzyl_detail=> detail)
    when "8"
      score.update_attributes( :rxxh=> value, :rxxh_detail=> detail)
    when "9"
      score.update_attributes( :zsxg=> value, :zsxg_detail=> detail)
    when "10"
      score.update_attributes( :zsgz=> value, :zsgz_detail=> detail)
    when "11"
      score.update_attributes( :rzzx=> value, :rzzx_detail=> detail)
    when "12"
      score.update_attributes( :xshd=> value, :xshd_detail=> detail)
    else
    end
    render :json=>1
  end

=end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/grade_helper.rb
module GradeHelper
end

app/views/grade/_feng_guan_zhuan_yuan.html.erb
<%= form_for @feng_score, url:{ action:"submit_fgzy"} do |f| %>
<div style=" border: 1px solid; padding:10px;">
	<div style="background-color:#948F94; height:50px; line-height:50px;">
       一、学术交流（满分45分，25分及以上为合格）
	</div>
	<div style="border: 1px solid; margin-top:20px; padding:10px; ">
		<div style="">
			1、学术会议（共25分）
		</div>
		<div style="text-align:left; padding:5px;">
		满足以下其中一个标准即可得满分：①承办或举办中华医学会分会年会或国际性学术会议；②承办中华医学会分会专题学术会议（含学组会等），注册参会人数A、类800人、B类500人、C类300人、D类200人，现场代表满意度70%以上。③举办“两岸三/四地（粤港澳台）”学术会议。其中省外注册参会人数须达到总参会人数10%以上，注册参会人数A类350人、B类250人、C类180人，D类120人，现场代表满意度70%以上。④举办或承办跨省区域性学术会议（含中南六省会议等）。注册参会人数A类350人、B类250人、C类180人、D类120人，其中省外注册参会人数不低于总参会人数10%，现场代表满意度70%以上。⑤举办专科分会学术年会，注册参会人数A类250人、B类200人、C类150人、D类100人，现场代表满意度70%以上。⑥举办专科分会青年委员学术会议、专题研讨会或分会学组会议两次以上。每次注册参会人数A类180人、B类150人、C类100人、D类80人，现场代表满意度70%以上。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'xshy_detail', :cols=>90, :rows=>7 , :class=>"detail"%>
	    <div>
	    	请输入您在此小项的评分（共25分）：
	    	<%= f.text_field 'xshy', :size=>10%>
	    	<button value="1" class="update_attr">确定</button>
	    	<button value="Modify" class="update_attr1">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			2、学术管理与组织管理部(满分7分)
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		满足其中一个标准即可得满分①举办国家、省、市级继教学习班，注册参加人数A类200人、B类120人、C类80人，现场代表满意度70%以上（若与学术会议合办，且满足以上条件加5分）；②举办读片会、病例讨论会、周三学术活动，一年3场以上（含3场），每场参会人数A类150人、B类100人、C类80人、D类50人。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'jxyx_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共10分）：
	    	<%= f.text_field 'jxyx',:size=>10%>
	    	<button value="2" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="background-color:#948F94; height:50px; line-height:50px;">
       二、专科分会组织管理工作（含会员发展;满分35分，合格20分以上（含20分））
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			3、按时提交年度计划和总结（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		按学会要求，每年准时提交年度计划和总结及相关报告（含论文、讲座等电子、影像资料，纪要），及学会要求上报的相关资料。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'astj_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'astj',:size=>10%>
	    	<button value="3" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			4、完成会员发展和服务工作(5分)
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		根据《广东省医学会章程》相关会员管理规定，完成会员发展和服务工作。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'wchy_detail',:cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'wchy',:size=>10%>
	    	<button value="4" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			5、执行会议制度（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		按《广东省医学会专科分会管理规定》，每年须召开一次全体委员会议，半年召开一次常务委员会议，严格执行考勤制度，做好会议纪要并及时上报。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'zxhy_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'zxhy',:size=>10%>
	    	<button value="5" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			6、遵纪守法，遵守学会规章制度（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		坚决贯彻执行国家的方针、法规、政策，依法守法。遵守学会的各项规章制度，执行准则，按规定办事，能较好地带领本专科分会开展工作。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'zjsf_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'zjsf',:size=>10%>
	    	<button value="6" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			7、打造一流的学术平台（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		充分发扬民主，全面听取各种意见，为广大会员提供公平、公正、公开的竞争机会。专科分会委员会专家团结，合作氛围好，重大工作事项经常务委员会或者全体委员会讨论。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'dzyl_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'dzyl',:size=>10%>
	    	<button value="7" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			8、热心学会工作，医德高尚（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		热心学会工作，尊重学会、工作责任心强，分会委员风气正派、学术水平高、医德高尚、廉洁自律、不利用职务便利谋取私利。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'rxxh_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'rxxh',:size=>10%>
	    	<button value="8" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="background-color:#948F94; height:50px; line-height:50px;">
       三、经费管理（满分20分，合格10分以上）
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			9、遵守相关财务管理规定（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		遵守学会相关财务管理规定。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'zsxg_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'zsxg',:size=>10%>
	    	<button value="9" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			10、招商工作规范（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		会议招商工作规范。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'zsgz_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'zsgz',:size=>10%>
	    	<button value="10" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			11、认真执行预、决算制度（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		会前5个工作日内提交预算，决算与预算相符。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'rzzx_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'rzzx',:size=>10%>
	    	<button value="11" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<div style="border: 1px solid; margin-top:20px;padding:10px; ">
		<div style="">
			12、学术活动结余较往年增长（5分）
		</div>
		<div style="text-align:left; padding:5px; padding:10px;">
		会前5个工作日内提交预算，决算与预算相符。
	    </div>
	    <hr/>
	    <div>
	    	请陈述理由和履行情况
	    </div>
	    <%= f.text_area 'xshd_detail', :cols=>90, :rows=>7 %>
	    <div>
	    	请输入您在此小项的评分（共5分）：
	    	<%= f.text_field 'xshd',:size=>10%>
	    	<button value="12" class="update_attr">确定</button>
	    	<button value="Modify">修改</button>
	    </div>
	</div>
	<%= f.submit '提交' %>
</div>
<% end %>

<script>
$(".update_attr").click(function(){
	var flag= $(this).val();
	var value= $(this).prev().val();
	var detail= $(this).parent().prev().val();
	var party= $("#parties_select").val();

});

$('form').validate({
	rules:{
		"feng_score[xshy]" : { required:true, range:[0,25]},
		"feng_score[jxyx]" : { required:true, range:[0,7]},
		"feng_score[astj]" : { required:true, range:[0,5]},
		"feng_score[wchy]" : { required:true, range:[0,5]},
		"feng_score[zxhy]" : { required:true, range:[0,5]},
		"feng_score[zjsf]" : { required:true, range:[0,5]},
		"feng_score[dzyl]" : { required:true, range:[0,5]},
		"feng_score[rxxh]" : { required:true, range:[0,5]},
		"feng_score[zsxg]" : { required:true, range:[0,5]},
		"feng_score[zsgz]" : { required:true, range:[0,5]},
		"feng_score[rzzx]" : { required:true, range:[0,5]},
		"feng_score[xshd]" : { required:true, range:[0,5]}
	},
	messages:{
		"feng_score[xshy]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[jxyx]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[astj]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[wchy]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[zxhy]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[zjsf]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[dzyl]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[rxxh]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[zsxg]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[zsgz]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[rzzx]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
		"feng_score[xshd]": { required:"请填入必填项后再提交！",
	                          range:"您所填写数字超出范围！"},
	},
	errorPlacement: function( error, element){
		$(error).addClass("error");
		error.appendTo( element.parent());
	}
});
</script>

app/views/grade/_leave_message.html.erb
<div>
	<h1>意见箱</h1>
	<p align="left">欢迎提意见，请在下面输入您的宝贵意见，我们有专人负责查收和整理 </p>
	<%= text_area_tag 'message', nil, cols:90, rows:7 , class:"message", value:"message"%>
	    <br/>
	<button value="1" id="leave_message">留言</button>
</div>
<script>
  $("#leave_message").click( function(){
  	var message= $("#message").val();
  	$.ajax({
  		url: '/grade/leave_message',
  		data: 'message='+message,
  		success: function(json){
  			alert("留言成功。");
  		}
  	});
  });
</script>

app/views/grade/_ping_feng_qing_kuang.html.erb
<div style=" border: 1px solid; padding:10px;">
	<div style=" border: 1px solid;">
		<div style="background-color:#948F94; height:50px; line-height:50px;">
	       一、学术交流（满分45分，25分及以上为合格）
		</div>
		<div>
			<table>
				<tr>
					<td>1、学术会议（满分25分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>2、学术管理与组织管理部(满分7分)</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>3、继续教育部(满分3分)</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>4、直通车（10分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
			</table>
		</div>
	</div>

	<div style=" border: 1px solid;">
		<div style="background-color:#948F94; height:50px; line-height:50px;">
	       二、专科分会组织管理工作（含会员发展，满分35分，20分及以上为合格）
		</div>
		<div>
			<table>
				<tr>
					<td>5、按时提交年度计划和总结（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>6、完成会员发展和服务工作(5分)</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>7、执行会议制度（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>8、认真完成学会交办工作（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>9、遵纪守法，遵守学会规章制度（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>10、打造一流的学术平台（5分））</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>11、热心学会工作，医德高尚（5分））</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
			</table>
		</div>
    </div>

	<div style=" border: 1px solid;">
		<div style="background-color:#948F94; height:50px; line-height:50px;">
	       三、经费管理（满分20分，合格10分以上）
		</div>
		<div>
			<table>
				<tr>
					<td>12、遵守相关财务管理规定（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>13、招商工作规范（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>14、认真执行预、决算制度（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>15、学术活动结余较往年增长（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
			</table>
		</div>
	</div>
	<div style=" border: 1px solid;">
		<div style="background-color:#948F94; height:50px; line-height:50px;">
	       四、附加分（满分30分）
		</div>
		<div>
			<table>
				<tr>
					<td>16、主持国家863计划、国家973计划、国家支撑计划项目、国家重大专项（4分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>17、主持国家中医药课题、国家自然科学基金（2分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>18、主持广东省自然科学基金（1分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>19、发表SCI论文（IF＞10），通讯作者或者第一作者（3分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>20、学术专著及卫生部、教育部指定的全国统编高校教材，国家级出版社出版的（2分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>21、科普专著（20万字以上），国家级出版社出版（2分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>22、国家自然、发明、进步奖，一等奖计5分，二等奖计4分，三等奖计3分</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>
					23、省部级自然、发明、进步奖，一等奖计3分，二等奖计2分，三等奖计1分。</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>24、荣誉或表彰（3分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>25、全国学术地位  （3分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>26、促进学术交流最多不超过6分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>27、建言献策（5分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
				<tr>
					<td>28、医学科普活动（3分）</td>
					<td>当前得分：**分</td>
					<td>未完成</td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/grade/error_state.html.erb
error_state

app/views/grade/feng_guan_zhuan_yuan.html.erb
<script >
  $( function(){
  	$("#tabs").tabs();
  });
</script>
<div style="text-align:center; width:70%; float:right; ">
<div id="tabs">
	<ul>
	<li><a href="#tabs-1">评分区</a></li>
	<li><a href="#tabs-2">查看评分情况</a></li>
	<li><a href="#tabs-3">我要提意见</a></li>
	</ul>
	<div id="tabs-1">
	<%= render partial: 'grade/feng_guan_zhuan_yuan' %>
	</div>
	<div id="tabs-2">
	<%= render partial: 'grade/ping_feng_qing_kuang' %>
	</div>
	<div id="tabs-3">
	<%= render partial: 'grade/leave_message' %>
	</div>
</div>
</div>

app/views/grade/feng_guan_zhuan_yuan.js.erb
$("#tabs-1").html("<%= escape_javascript(render('grade/feng_guan_zhuan_yuan')) %>")

app/views/grade/index.html.erb
<div style="width:400px; height:300px; text-align:center; margin: 0 auto; margin-top: 10%;">
	<h3>登录</h3>
	<hr>
	<%= form_for @user, url: grade_enter_path do |f|%>
      <%= f.label "用户名：" %>
      <%= f.text_field :username %>
      <br/>
      <%= f.label "密码：" %>
      <%= f.password_field :password %>
      <br/>
 	  <%= f.submit "进入", :class=>"btn btn-primary" %>
    <hr>
    <%end%>
</div>

app/views/layouts/_header.html.erb
  <h4><%= @user.username %>，欢迎您</h4>
  <hr/>

app/views/layouts/_right_side_list.html.erb
<div style="float:right; width:15%; border:1px solid; padding: 4px;">
	<div id="right_header" style="border: 1px solid; padding: 4px;">
	  心血管分会委员评分情况一览表
    </div>
    总共：<p id="right_total"></p>
    填报：<p id="right_done"></p>
    未填报：<p id="right_undone"></p>
    填报率：<p id="right_rate"></p>
    <hr/>
    填报名单：<br/>
    <div id="right_done_list">
    </div>
    <hr/>
    未填报名单：<br/>
    <div id="right_undone_list">
    </div>
</div>